### ISSUE TITLE
@hook 'after_request' is not working for errors

### ISSUE THREAD

**Issue by mrdc** [bottlepy/bottle#1338] opened 2021-04-21 10:59 UTC
Hi,

@hook('after_request') is not working for errors: 404, for example.

```python

@hook('after_request')
def enable_cors():
    response.headers['Access-Control-Allow-Origin'] = '*'

@error(404)
def error404(error):
    return '404'
```

**Comment by defnull** [comment] 2021-07-07 11:31
Fixed in master branch, hard to fix in 0.12 without breaking stuff. The problem is that errors or explicitly returning `HTTPResponse` will bypass any headers already set in the global `response` object. This is by design. The `after_request` hook is called too early in 0.12 (before merging the `HTTPResponse` back into `response`).

**Closed** 2021-09-28 15:29 UTC
